import { z } from "zod";

export const mappings = {
  "react.js": "react",
  reactjs: "react",
  react: "react",
  "next.js": "nextjs",
  nextjs: "nextjs",
  next: "nextjs",
  "vue.js": "vuejs",
  vuejs: "vuejs",
  vue: "vuejs",
  "express.js": "express",
  expressjs: "express",
  express: "express",
  "node.js": "nodejs",
  nodejs: "nodejs",
  node: "nodejs",
  mongodb: "mongodb",
  mongo: "mongodb",
  mongoose: "mongoose",
  mysql: "mysql",
  postgresql: "postgresql",
  sqlite: "sqlite",
  firebase: "firebase",
  docker: "docker",
  kubernetes: "kubernetes",
  aws: "aws",
  azure: "azure",
  gcp: "gcp",
  digitalocean: "digitalocean",
  heroku: "heroku",
  photoshop: "photoshop",
  "adobe photoshop": "photoshop",
  html5: "html5",
  html: "html5",
  css3: "css3",
  css: "css3",
  sass: "sass",
  scss: "sass",
  less: "less",
  tailwindcss: "tailwindcss",
  tailwind: "tailwindcss",
  bootstrap: "bootstrap",
  jquery: "jquery",
  typescript: "typescript",
  ts: "typescript",
  javascript: "javascript",
  js: "javascript",
  "angular.js": "angular",
  angularjs: "angular",
  angular: "angular",
  "ember.js": "ember",
  emberjs: "ember",
  ember: "ember",
  "backbone.js": "backbone",
  backbonejs: "backbone",
  backbone: "backbone",
  nestjs: "nestjs",
  graphql: "graphql",
  "graph ql": "graphql",
  apollo: "apollo",
  webpack: "webpack",
  babel: "babel",
  "rollup.js": "rollup",
  rollupjs: "rollup",
  rollup: "rollup",
  "parcel.js": "parcel",
  parceljs: "parcel",
  npm: "npm",
  yarn: "yarn",
  git: "git",
  github: "github",
  gitlab: "gitlab",
  bitbucket: "bitbucket",
  figma: "figma",
  prisma: "prisma",
  redux: "redux",
  flux: "flux",
  redis: "redis",
  selenium: "selenium",
  cypress: "cypress",
  jest: "jest",
  mocha: "mocha",
  chai: "chai",
  karma: "karma",
  vuex: "vuex",
  "nuxt.js": "nuxt",
  nuxtjs: "nuxt",
  nuxt: "nuxt",
  strapi: "strapi",
  wordpress: "wordpress",
  contentful: "contentful",
  netlify: "netlify",
  vercel: "vercel",
  "aws amplify": "amplify",
};


export const feedbackSchema = z.object({
  totalScore: z.number(),
  categoryScores: z.array(
    z.object({
      name: z.string(),
      score: z.number(),
      comment: z.string(),
    }),
  ),
  strengths: z.array(z.string()),
  areasForImprovement: z.array(z.string()),
  finalAssessment: z.string(),
});

export const interviewCovers = [
  "/adobe.png",
  "/amazon.png",
  "/facebook.png",
  "/hostinger.png",
  "/pinterest.png",
  "/quora.png",
  "/reddit.png",
  "/skype.png",
  "/spotify.png",
  "/telegram.png",
  "/tiktok.png",
  "/yahoo.png",
];

export const dummyInterviews: Interview[] = [];

export const interviewTemplates = [
  {
    id: "template-liderazgo",
    role: "Líder de Equipo",
    level: "",
    type: "Conductual",
    techstack: [],
    questions: [
      "Contame sobre una situación en la que tuviste que liderar un equipo en un momento de presión o crisis. ¿Qué hiciste y cuál fue el resultado?",
      "¿Cómo manejás los conflictos entre miembros de tu equipo? Dame un ejemplo concreto.",
      "Describí una vez en la que tuviste que tomar una decisión difícil sin tener toda la información. ¿Cómo lo hiciste?",
      "¿Cómo motivás a las personas a tu cargo cuando el ambiente es desmotivante o hay mucha presión?",
      "Contame sobre un error que cometiste como líder y cómo lo resolviste.",
    ],
    finalized: true,
  },
  {
    id: "template-rrhh",
    role: "Recursos Humanos",
    level: "",
    type: "Conductual",
    techstack: [],
    questions: [
      "Describí una situación en la que tuviste que manejar un conflicto delicado entre empleados. ¿Cómo lo abordaste?",
      "¿Cómo priorizás cuando tenés múltiples procesos de selección activos al mismo tiempo?",
      "Contame sobre alguna vez que tuviste que comunicar una decisión difícil o impopular a los empleados.",
      "¿Cómo garantizás un proceso de selección justo e imparcial?",
      "Dame un ejemplo de cómo contribuiste a mejorar el clima laboral en tu organización.",
    ],
    finalized: true,
  },
  {
    id: "template-ventas",
    role: "Ejecutivo de Ventas",
    level: "",
    type: "Conductual",
    techstack: [],
    questions: [
      "Contame sobre la venta más difícil que lograste cerrar. ¿Qué hiciste para lograrlo?",
      "¿Cómo manejás el rechazo de un cliente? Dame un ejemplo de cómo lo convertiste en una oportunidad.",
      "Describí una situación en la que perdiste una venta importante. ¿Qué aprendiste?",
      "¿Cómo te organizás para cumplir tus metas mensuales cuando el pipeline está flojo?",
      "Contame sobre alguna vez que tuviste que manejar un cliente muy difícil o molesto.",
    ],
    finalized: true,
  },
  {
    id: "template-general",
    role: "Entrevista General",
    level: "",
    type: "Conductual",
    techstack: [],
    questions: [
      "Contame sobre vos: ¿quién sos profesionalmente y cuáles son tus principales fortalezas?",
      "Describí una situación en la que tuviste que adaptarte rápidamente a un cambio importante en el trabajo.",
      "¿Cómo manejás la presión y los plazos ajustados? Dame un ejemplo concreto.",
      "Contame sobre algún conflicto que hayas tenido con un compañero o jefe y cómo lo resolviste.",
      "¿Dónde te ves profesionalmente en los próximos tres años y por qué?",
    ],
    finalized: true,
  },
];
