import { z } from "zod";

export const mappings = {
  "react.js": "react",
  reactjs: "react",
  react: "react",
  "next.js": "nextjs",
  nextjs: "nextjs",
  next: "nextjs",
  "vue.js": "vuejs",
  vuejs: "vuejs",
  vue: "vuejs",
  "express.js": "express",
  expressjs: "express",
  express: "express",
  "node.js": "nodejs",
  nodejs: "nodejs",
  node: "nodejs",
  mongodb: "mongodb",
  mongo: "mongodb",
  mongoose: "mongoose",
  mysql: "mysql",
  postgresql: "postgresql",
  sqlite: "sqlite",
  firebase: "firebase",
  docker: "docker",
  kubernetes: "kubernetes",
  aws: "aws",
  azure: "azure",
  gcp: "gcp",
  digitalocean: "digitalocean",
  heroku: "heroku",
  photoshop: "photoshop",
  "adobe photoshop": "photoshop",
  html5: "html5",
  html: "html5",
  css3: "css3",
  css: "css3",
  sass: "sass",
  scss: "sass",
  less: "less",
  tailwindcss: "tailwindcss",
  tailwind: "tailwindcss",
  bootstrap: "bootstrap",
  jquery: "jquery",
  typescript: "typescript",
  ts: "typescript",
  javascript: "javascript",
  js: "javascript",
  "angular.js": "angular",
  angularjs: "angular",
  angular: "angular",
  "ember.js": "ember",
  emberjs: "ember",
  ember: "ember",
  "backbone.js": "backbone",
  backbonejs: "backbone",
  backbone: "backbone",
  nestjs: "nestjs",
  graphql: "graphql",
  "graph ql": "graphql",
  apollo: "apollo",
  webpack: "webpack",
  babel: "babel",
  "rollup.js": "rollup",
  rollupjs: "rollup",
  rollup: "rollup",
  "parcel.js": "parcel",
  parceljs: "parcel",
  npm: "npm",
  yarn: "yarn",
  git: "git",
  github: "github",
  gitlab: "gitlab",
  bitbucket: "bitbucket",
  figma: "figma",
  prisma: "prisma",
  redux: "redux",
  flux: "flux",
  redis: "redis",
  selenium: "selenium",
  cypress: "cypress",
  jest: "jest",
  mocha: "mocha",
  chai: "chai",
  karma: "karma",
  vuex: "vuex",
  "nuxt.js": "nuxt",
  nuxtjs: "nuxt",
  nuxt: "nuxt",
  strapi: "strapi",
  wordpress: "wordpress",
  contentful: "contentful",
  netlify: "netlify",
  vercel: "vercel",
  "aws amplify": "amplify",
};


export const feedbackSchema = z.object({
  totalScore: z.number(),
  categoryScores: z.array(
    z.object({
      name: z.string(),
      score: z.number(),
      comment: z.string(),
    }),
  ),
  strengths: z.array(z.string()),
  areasForImprovement: z.array(z.string()),
  finalAssessment: z.string(),
});

export const interviewCovers = [
  "/adobe.png",
  "/amazon.png",
  "/facebook.png",
  "/hostinger.png",
  "/pinterest.png",
  "/quora.png",
  "/reddit.png",
  "/skype.png",
  "/spotify.png",
  "/telegram.png",
  "/tiktok.png",
  "/yahoo.png",
];

export const dummyInterviews: Interview[] = [];

export const GENERAL_BEHAVIORAL_QUESTIONS = [
  "Cuéntame sobre ti.",
  "¿Qué te motivó a postularte para este cargo?",
  "Cuéntame 2 de tus principales fortalezas y 2 de tus principales debilidades.",
  "Describe una situación en la que tuviste que adaptarte rápidamente a un cambio. ¿Cómo lo manejaste?",
  "Cuéntame sobre una experiencia en la que trabajaste en equipo. ¿Cuál fue tu rol y qué aprendiste de esa experiencia?",
  "¿Cómo manejas situaciones de estrés en el trabajo? Proporcióname un ejemplo.",
  "Describe una situación en la que tuviste que comunicar una idea compleja a alguien. ¿Cómo lo hiciste?",
  "¿Has propuesto alguna idea innovadora en tu trabajo o estudios? ¿Cómo fue recibida?",
  "Cuéntame sobre una vez en que tomaste la iniciativa en un proyecto. ¿Qué hiciste?",
  "Describe una decisión difícil que tuviste que tomar. ¿Cuál fue el proceso que seguiste?",
];

export const interviewTemplates = [
  {
    id: "template-general",
    role: "Competencias Generales",
    level: "",
    type: "Conductual",
    techstack: [],
    questions: GENERAL_BEHAVIORAL_QUESTIONS.slice(0, 5),
    finalized: true,
  },
  {
    id: "template-secretariado",
    role: "Secretariado Gerencial",
    level: "",
    type: "Conductual + Cargo",
    techstack: [],
    questions: [
      "Cuéntame sobre una vez que organizaste una actividad o agenda para otra persona o grupo. ¿Qué hiciste? ¿Qué herramientas usaste? ¿Cómo resultó?",
      "Relátame una situación en la que tuviste que manejar información importante o delicada. ¿Qué tipo de información era? ¿Cómo actuaste para mantenerla segura?",
      "Háblame de una ocasión en la que redactaste o preparaste un documento formal. ¿Para quién era? ¿Qué te dijeron sobre el resultado?",
      "Cuéntame cómo organizas tus tareas cuando tienes varias actividades al mismo tiempo. ¿Qué haces primero? ¿Cómo decides qué priorizar?",
      "Describe una situación en la que lograste que un grupo trabajara de forma coordinada. ¿Qué rol asumiste? ¿Qué herramientas usaste?",
    ],
    finalized: true,
  },
  {
    id: "template-rrhh",
    role: "Auxiliar de Recursos Humanos",
    level: "",
    type: "Conductual + Cargo",
    techstack: [],
    questions: [
      "Cuéntame cómo participarías en un proceso de bienvenida a nuevos practicantes. ¿Qué sugerirías?",
      "Háblame de una vez que tuviste que guardar una información personal y no compartirla.",
      "Relata una situación en la que alguien tuvo un problema y tú actuaste para orientarlo o escucharlo.",
      "Cuéntame cómo organizarías los documentos de varios compañeros en una base de datos o carpeta.",
      "Háblame de una vez que participaste en una actividad de bienestar, integración o recreación. ¿Qué hiciste?",
    ],
    finalized: true,
  },
  {
    id: "template-almacen",
    role: "Auxiliar de Almacén y Bodega",
    level: "",
    type: "Conductual + Cargo",
    techstack: [],
    questions: [
      "Cuéntame sobre una vez que organizaste materiales o implementos en un espacio físico.",
      "Relata una situación en la que hubo una diferencia en el conteo de elementos. ¿Qué hiciste?",
      "Háblame de una ocasión en la que tuviste que entregar algo con urgencia. ¿Cómo actuaste?",
      "Describe cómo garantizarías la limpieza y seguridad en una zona de almacenamiento.",
      "Cuéntame cómo actuarías si algo no estuviera registrado correctamente en una lista.",
    ],
    finalized: true,
  },
  {
    id: "template-admin",
    role: "Asistente Administrativo",
    level: "",
    type: "Conductual + Cargo",
    techstack: [],
    questions: [
      "Cuéntame sobre una vez que tuviste que planear o coordinar una actividad o evento. ¿Cómo lo organizaste? ¿Qué aprendiste?",
      "Háblame de una situación donde priorizaste tareas para cumplir con varios compromisos. ¿Qué herramientas o estrategias usaste?",
      "Relata un caso en el que propusiste una mejora para hacer algo más rápido o eficiente. ¿Qué observaste? ¿Cómo lo comunicaste?",
      "Cuéntame sobre un momento en el que cometiste un error al entregar un trabajo. ¿Cómo lo resolviste? ¿Qué aprendiste?",
      "Describe un día en el que tuviste muchas responsabilidades. ¿Cómo lo manejaste? ¿Qué técnicas de organización usaste?",
    ],
    finalized: true,
  },
];
